### ISSUE TITLE
Fix remaining commonmark tests

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystjs#37]
Current failing cmark json tests:
```
// Expected
44, // This is a block break, expect it to be different
// Minor
25, // This is a &nbsp; I think
// To fix
333, // Spacing around inline code?
353, // Broken paragraph/emph?
506, // This is a link issue?
```

**Comment by fwkoch** [comment]
333: The problem here is quite clear - we are prioritizing the `*` as a bullet rather than the open to an emphasis.
```
  - title: Emphasis and strong emphasis - example 353
    mdast:
      type: root
      children:
        - type: list
          ordered: false
          spread: false
          children:
            - type: listItem
              spread: true
              children:
                - type: text
                  value: a *
    myst: |
      * a *
    html: |
      <p>* a *</p>
```

**Comment by fwkoch** [comment]
333: Losing whitespace

Current:
```
  - title: Code spans - example 333
    mdast:
      type: root
      children:
        - type: paragraph
          children:
            - type: inlineCode
              value: b
    myst: |
      ` b `
    html: |
      <p><code> b </code></p>
```
Expected:
```
  - title: Code spans - example 333
    mdast:
      type: root
      children:
        - type: paragraph
          children:
            - type: inlineCode
              value: ' b '
    myst: |
      ` b `
    html: |
      <p><code> b </code></p>
```
